version: '3.5'
services:
  mysql:
    container_name: mysql
    image: mysql
    command:
      - --default-time-zone=America/Mexico_city
      - --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: general
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin5263
      MYSQL_ROOT_PASSWORD: King5263,
      TZ: America/Mexico_city
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
    networks:
      - dockerNetwork
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: King5263
      MONGO_INITDB_DATABASE: test
    volumes:
      - $PWD/mongo:/data/db
    networks:
      - dockerNetwork
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - dockerNetwork
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - dockerNetwork
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks: 
  dockerNetwork:
    driver: bridge